### ISSUE TITLE
Superposition VLI1 et VLI2 au CSP

### ISSUE THREAD

**Issue by Superjajaman75** [Superjajaman75/MOD-CSP-IRG#9]
Quand retour caserne des VLI, risque de superposition des véhicules.

Submitted by @alex59167

**Comment by Spyro546** [comment]
Bug lié au script d'init qui inverse les deux VLM dans le CSP. Le placement est inversé par rapport à leur emplacement défini dans le script de retour caserne

**Comment by Superjajaman75** [comment]
Corrigé dans la version dev
